### ISSUE TITLE
Дублирование напоминаний

### ISSUE THREAD

**Issue by Pr0Chris** [CrezZ/OsuRasp#2]
Дублирование напоминаний вне времени и пространства http://prntscr.com/luuqs1 
При настройках выставленных напоминать за 30 минут до начала пары http://prntscr.com/luurxw

**Comment by CrezZ** [comment]
В новой версии мы уже вроде пофиксили, нужнен тест

**Comment by CrezZ** [comment]
Баг был подтвержден, пофиксен. Время таки тоже отрицательное бывает
